branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: github-actions-course-demo
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: gha-course
  repository: null
  sc: git
  workspace_type: Application
